version: "3.7"

services:
  influxdb:
    image: influxdb
    environment:
      - INFLUXDB_DB=home
      - INFLUXDB_USER=user
      - INFLUXDB_USER_PASSWORD=password
    volumes:
      - ./influx_data:/var/lib/influxdb

#  nginx:
#    image: nginx:1.15-alpine
#    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - ./config/nginx:/etc/nginx/conf.d
#      - ./config/certbot/conf:/etc/letsencrypt
#      - ./config/certbot/www:/var/www/certbot
#
#  certbot:
#    image: certbot/
#    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
#    volumes:
#      - ./config/certbot/conf:/etc/letsencrypt
#      - ./config/certbot/www:/var/www/certbot

  chronograf:
    image: chronograf:alpine
    ports:
      - 80:8888
    volumes:
      - ./config/chronograf:/var/lib/chronograf
    environment:
      - VIRTUAL_HOST=msquare.dev
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=msquare.dev
      - LETSENCRYPT_EMAIL=maxi.mueller@me.com
    links:
      - influxdb

  telegraf:
    image: telegraf
    privileged: true
    volumes:
      - ./config/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    environment:
      - USER=user
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_PASSWORD=password
    links:
      - influxdb
      - mqtt-broker

  mqtt-broker:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 9001:9001