version: "3.7"

services:
  influxdb:
    image: influxdb
    environment:
      - INFLUXDB_DB=home
      - INFLUXDB_USER=user
      - INFLUXDB_USER_PASSWORD=password
    volumes:
      - ./influx_data:/var/lib/influxdb
    networks:
      - influx

  chronograf:
    image: chronograf:alpine
    # ports:
    #   - 8082:8888
    volumes:
      - ./config/chronograf:/var/lib/chronograf
    # environment:
      # - AUTH_DURATION=1h
      # - GH_CLIENT_ID=61b13f1fd9a4c4c20b8d
      # - GH_CLIENT_SECRET=3be64b28f665ec73f2f6b9734c50826717b97549
      # - GH_ORGS=aalto-exchange
      # - TOKEN_SECRET=maischkesselfluffert
    deploy:
      replicas: 1
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain=beer.msquare.dev
        - com.df.servicePath=/
        - com.df.srcPort=443
        - com.df.port=8888
        - com.df.letsencrypt.host=beer.msquare.dev
        - com.df.letsencrypt.email=gedoensmax@googlemail.com
        - com.df.users=aaltobrewing:hipphopp
    networks:
      - influx
      - proxies

  telegraf:
    image: telegraf:alpine
    volumes:
      - ./config/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - USER=user
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_PASSWORD=password
    networks:
      - influx

  mqtt-broker:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      - influx

  kapacitor:
    image: kapacitor 
    ports: 
      - 9092:9092
    environment:
      - KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086
      - KAPACITOR_HOSTNAME=kapacitor
    volumes:
      - ./config/kapacitor.config:/etc/kapacitor/kapacitor.conf:ro
      - ./kapacitor_data:/var/lib/kapacitor
    networks:
      - influx

networks:
  proxies:
    external: true
  influx:
